# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    http_client:
        scoped_clients:
            api_layer.client:
                base_uri: 'http://data.fixer.io/api/'
                max_redirects: 10
                max_duration: 0
                http_version: 1.1
                query:
                    access_key: '%env(FIXER_ACCESS_KEY)%'
            open_exchange_rates.client:
                base_uri: 'https://openexchangerates.org/api/'
                max_redirects: 10
                max_duration: 0
                http_version: 1.1
                query:
                    app_id: '%env(OPENEXCHANGERATES_ACCESS_KEY)%'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
