version: '3.7'
services:
    http:
        image: nginx:alpine3.18
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
        depends_on:
            - app
    app:
        build: ./docker/app
        volumes:
            - .:/var/www
        depends_on:
            - db

    ###> doctrine/doctrine-bundle ###
    db:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
