version: '3.7'
services:
    http:
        image: nginx:alpine3.18
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
        depends_on:
            - app
    app:
        build: ./docker/app
        volumes:
            - .:/var/www
